### ISSUE TITLE
Can't figure out failure

### ISSUE THREAD

**Issue by jasonrichardsmith** [GoogleContainerTools/krew#126]
I am not sure what failure I am experiencing with this plugin.  Errors seem to be concatenated against each other.
https://github.com/jasonrichardsmith/krew-index/blob/initial-submission/plugins/rbac-view.yaml
```
$ kubectl krew install --manifest=rbac-view.yaml
Installing plugin: rbac-view
W1019 10:03:04.251654   14926 install.go:132] failed to install plugin "rbac-view": failed to dowload and move during installation: failed to download and verify file: failed to create file "/tmp/krew-downloads/rbac-view/bin/linux/rbac-view": open /tmp/krew-downloads/rbac-view/bin/linux/rbac-view: no such file or directory
F1019 10:03:04.251778   14926 root.go:52] failed to install some plugins: [rbac-view]
```

**Comment by ahmetb** [comment]
Looking. It looks like a bug in our tar.gz extraction code, which wasn't battle-tested.

**Comment by ahmetb** [comment]
Looks like our .tar.gz files we used for testing included the "directory" entries in the tarball. However it's possible to create tarballs without directory entries, yet have files with nested paths, like:

    tar czvf foo.tar.gz dir1/dir2/file

Looks like we aren't handling this.
