### ISSUE TITLE
Handle "krew remove krew"

### ISSUE THREAD

**Issue by lbb** [GoogleContainerTools/krew#129]
Krew by design can't remove itself. We need to handle the case that someone wants to remove krew itself.

```
$ krew remove krew
krew can't remove krew. Please run:
    rm -r <krew-path>

$ echo $?
1
```

**Comment by Zyqsempai** [comment]
Sounds like a `good first issue' I can take care of it.

**Comment by ahmetb** [comment]
@Zyqsempai sounds good!
