### ISSUE TITLE
Completion for plugins

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/krew#155]
# Expected behavior
Plugins are included in kubectl subcommand completion: `kubectl <tab><tab>`.
Also, for plugins supporting command completion, `kubectl some-plugin --<tab><tab>` should list the available options, as if invoked as a stand-alone tool.

# Actual behavior
Plugin names and plugin options are not suggested by command completion. This makes plugins much harder to use and discover, because those commands are more seldomly used anyway.

**Comment by ahmetb** [comment]
Please suggest this on kubernetes/kubectl repo.

**Comment by ICHx** [comment]
This is possible now with https://github.com/kubernetes/kubernetes/pull/105867 and https://github.com/marckhouzam/kubectl-plugin_completion
