### ISSUE TITLE
Krew install fails on Ubuntu WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by StianOvrevage** [GoogleContainerTools/krew#159]
```
# (
>   set -x; cd "$(mktemp -d)" &&
>   curl -fsSLO "https://storage.googleapis.com/krew/v0.2.1/krew.{tar.gz,yaml}" &&
>   tar zxvf krew.tar.gz &&
>   ./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" install \
>     --manifest=krew.yaml --archive=krew.tar.gz
> )
++ mktemp -d
+ cd /tmp/tmp.y04kz5whCK
+ curl -fsSLO 'https://storage.googleapis.com/krew/v0.2.1/krew.{tar.gz,yaml}'
+ tar zxvf krew.tar.gz
./krew-darwin_amd64
./krew-linux_amd64
./krew-linux_arm
./krew-windows_amd64.exe
++ uname
++ tr '[:upper:]' '[:lower:]'
+ ./krew-linux_amd64 install --manifest=krew.yaml --archive=krew.tar.gz
Installing plugin: krew
W0311 13:32:17.764882     418 install.go:132] failed to install plugin "krew": failed to dowload and move during installation: could not rename file from "/tmp/krew-temp-move308169657" to "/root/.krew/store/krew/dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a": rename /tmp/krew-temp-move308169657 /root/.krew/store/krew/dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a: permission denied
F0311 13:32:17.768004     418 root.go:52] failed to install some plugins: [krew]
```

Tried as root and non-root. Both fails with same error.

**Comment by ahmetb** [comment]
See #156.

**Comment by StianOvrevage** [comment]
I reviewed that ticket before opening and I do not think they are the same.

**Comment by HoveringHalibut** [comment]
@StianOvrevage The issue is with the length of the underlying NTFS path of the WSL root directory, whose mount defaults to deep in your windows profile.  With the additional krew folder depth and long length of the folder name, the full path exceeds the [Windows MAX_PATH](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation) length of 260.

I worked around the issue by moving my /home mount to a directory in the root of C:

This is using the WSL Ubuntu image:

/etc/fstab
`LABEL=cloudimg-rootfs   /        ext4   defaults        0 0`
`C:      /mnt/c  drvfs   rw,noatime,uid=1000,gid=1000,umask=22,fmask=11  0       0`
`/mnt/c/linuxhome        /home   drvfs   bind    0       0`

/etc/wsl.conf
`[automount]`
`mountFsTab = true`

**Comment by ahmetb** [comment]
@StianOvrevage can you give an example of a full path exceeding MAX_PATH? I'm curious how it looks like witht he additional krew folder depth.

**Comment by StianOvrevage** [comment]
Great job figuring this out!

I was not able to get automatic mounting of `/home` to work. There was no `wsl.conf` so maybe there are some differences between our setups.

I did however just mount `/mnt/c/linuxhome` temporarily for the install and then moved `krew` into `/krew`. Hopefully this works without breaking too many of `krew`s expectations about how things should look.

**Comment by ahmetb** [comment]
If any of you could write up summary a summary of the WSL issue, I would like to link to it from the README>Installation section as a "Known issue with WSL".

**Comment by StianOvrevage** [comment]
@ahmetb I don't know enough about WSL to actually find the underlying path as mapped to the NTFS disk.

According to https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/ at some point it was at `%LocalAppData%\lxss\rootfs` but I do not have that folder on my machine. That path would translate to `C:\Users\Stian\AppData\Local\lxss\rootfs` here.

**Comment by ahmetb** [comment]
`echo 'C:\Users\Stian\AppData\Local\lxss\rootfs\home/MYUSERNAME/.krew/store01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b/store/plugin-name/kubectl-plugin-name' | wc -c` is around ~170 chars, not sure if it could easily reach 260 chars as long as your user name is very long.

**Comment by HoveringHalibut** [comment]
@StianOvrevage wsl.conf doesn't exist by default, you can just create it.

@ahmetb The full patch for me is only 214, now that I actually counted.
`C:\Users\halibuthh\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\halibuthh\.krew\store\krew\dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a\krew`

What's odd is that it is a permission error and I traced all the system calls and they looked fine from a user permissions stand-point.  It could just be a bad error message.

It was a bit for naught anyway, pending this fix for kubectl executing plugins in WSL:
https://github.com/kubernetes/kubernetes/pull/76227

**Comment by alioSHA512** [comment]
This Worked for me,
https://github.com/kubernetes-sigs/krew/issues/159#issuecomment-480913080

But I don't want to move my /home directory, so I created dir `/mnt/c/krew` and linked it to `~/.krew`, and that did the trick.

```
$ ln -s /mnt/c/krew/ ~/.krew
```
