### ISSUE TITLE
Document Style Guide/Enforcement for the index repo

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/krew#24]
The centralized krew-index repo started to get many pull requests.  So far the #1 issue is:

1. What constitutes a plugin that can be in the central index?
2. Why a plugin name is OK or NOT OK in the central index?

I suggest we explain GOOD/BAD names by recommending people with example suggestions in a Style Guide that improves over time.

cc: @lbb.

**Comment by ahmetb** [comment]
Done in #25.

**Comment by lbb** [comment]
This should be closed
