### ISSUE TITLE
Support more download formats than zip

### ISSUE THREAD

**Issue by robscott** [GoogleContainerTools/krew#34]
For a lot of Go projects, binary releases are either available directly or in a `.tar.gz` format. With how many k8s related projects are written in Go, it seems like it would make sense to add support for those formats. As an example, I'm using goreleaser to release [rbac-lookup](https://github.com/reactiveops/rbac-lookup). That defaults to `.tar.gz` formats for Mac and Linux releases. Even just supporting downloading binaries directly without trying to unzip them would likely be helpful (and very straightforward).  I'm happy to do some work in this direction if this is a feature if there's interest.

**Comment by ahmetb** [comment]
https://github.com/GoogleContainerTools/krew/blob/c9654cff81d174bc125721864b36551cbad25690/docs/KREW_ARCHITECTURE.md#plugin-package-format says we support `.tar.gz` but it looks like this is not implemented.
