### ISSUE TITLE
Migrate to pkg/errors

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/krew#73]
We should migrate to http://github.com/pkg/errors sometime. We have a lot of error message consistencies such as:

- `something bad happened, err: %v`
- `something bad happened, err=%+v`
- `something bad happened: %v`

This would involve:

1. Standardize wrapping errors.
2. Format errors with `%+v` where appropriate to print the stack trace.

**Comment by bvwells** [comment]
@ahmetb, I can take a look at this...

**Comment by ahmetb** [comment]
@bvwells argh too late. I couldn't resist the temptation and did it myself. PR incoming.

**Comment by bvwells** [comment]
Too bad. Maybe next time!
