### ISSUE TITLE
Remove directory indirection from krew.zip

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/krew#90]
Right now krew.zip has the following structure

```
unzip -l out/krew.zip
drwxr-xr-x  3.0 unx        0 b- stor 18-Oct-10 23:17 out/bin/
-rwxr-xr-x  3.0 unx 11682304 b- defN 18-Oct-10 23:17 out/bin/krew-windows_amd64.exe
-rwxr-xr-x  3.0 unx 11716104 b- defN 18-Oct-10 23:17 out/bin/krew-darwin_amd64
-rwxr-xr-x  3.0 unx 10214825 b- defN 18-Oct-10 23:17 out/bin/krew-linux_arm
-rwxr-xr-x  3.0 unx 11828176 b- defN 18-Oct-10 23:17 out/bin/krew-linux_amd64
```

The `out/` prefix in the .zip yaml is unnecessary. I'm even thinking `bin/` is redundant, too. 

We can keep `bin/` in case we add other stuff to the release someday, but I think it doesn't matter that much.

Fixing this would
- make copy operations in hack/krew.yaml shorter
- make installation instructions look shorter/cleaner

/cc @lbb; wdyt?

**Comment by lbb** [comment]
As mentioned earlier we should rename the output directory to something more common like `dist/`. I agree that we can have a flat folder structure in this folder.

```text
dist/
dist/krew-windows_amd64.exe
dist/krew-darwin_amd64
dist/krew-linux_arm
...
```

Depending on the build matrix we want to split the krew build outputs according to the architecture?

```text
dist/amd64/krew-windows.exe
dist/amd64/krew-darwin
dist/arm/krew-linux
...
```

**Comment by ahmetb** [comment]
I think flat is ok, no need to split by os/arch.

What I'm saying is, inside the zip, there shouldn't be a `dist/` folder. When you extract the zip into a dir, krew*.exe should be right there.
